GET http://localhost:3002/

###
POST http://localhost:3002/todo/huuu

###
PUT http://localhost:3002/true/ejege

###
PUT  http://localhost:3002/false/eje

###
DELETE http://localhost:3002/delete/eje

###
GET back-todo.vercel.app/getall

###
DELETE http://localhost:3002/removeall